---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  namespace: ns1
  labels:
    type: proxy
spec:
  containers:
    - name: httpd-con
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 1122
