---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deply
  labels:
    type: cms
spec:
  replicas: 2
  selector:
    matchLabels:
      type: cms
  template:
    metadata:
      name: ghost
      labels:
        type: cms
    spec:
      containers:
        - name: ghost-cm
          image: ghost
          ports:
            - containerPort: 2368
              hostPort: 9090
          env:
            - name: NODE_ENV
              value: development
