---
apiVersion: v1
kind: Pod
metadata:
  name: myjen
  labels:
    name: jeny
spec:
  containers:
    - name: myjen
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 9090
