---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    type: result-app
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    typr: result-app
